from fastmcp import FastMCP
from typing import List, Dict, Any

import json
from pathlib import Path

mcp = FastMCP("Stripe_Billing")

# Mock billing records, generated by scripts/generate_mock_data.py
DATA_PATH = Path(__file__).resolve().parent / "data" / "billing_records.json"
MOCK_BILLING_DATA = json.loads(DATA_PATH.read_text(encoding="utf-8"))


@mcp.tool
def search_billing_records(query: str) -> List[Dict[str, Any]]:
    """Search Stripe billing records by company legal name or billing email."""
    query = query.lower()
    return [
        dict(record) for record in MOCK_BILLING_DATA
        if query in record["legal_name"].lower() or query in record["billing_email"].lower()
    ]


if __name__ == "__main__":
    mcp.run()
