from fastmcp import FastMCP
from typing import List, Dict, Any

import json
from pathlib import Path

# 1. Initialize the FastMCP Server
mcp = FastMCP("Salesforce_CRM")

# 2. Mock CRM records, generated by scripts/generate_mock_data.py
DATA_PATH = Path(__file__).resolve().parent / "data" / "crm_records.json"
MOCK_CRM_DATA = json.loads(DATA_PATH.read_text(encoding="utf-8"))


# 3. Expose the Tool using the decorator
@mcp.tool
def search_crm_records(query: str) -> List[Dict[str, Any]]:
    """Search Salesforce CRM records by company name or website domain."""
    query = query.lower()
    return [
        dict(record) for record in MOCK_CRM_DATA
        if query in record["company_name"].lower() or query in record["website"].lower()
    ]


if __name__ == "__main__":
    mcp.run()
